### PR TITLE
Design cleanup + typography improvements

### LINKED ISSUE #3: Improve typography across website
- Spacing
- Colors
- Code blocks

### PR DESCRIPTION
**Pull request by chrzrdx**
Closes #3 

**Design decisions**

- [x] Fonts
- [x] Colors
- [x] Typography
- [x] Tailwind theme set up
- [x] Prose
- [ ] Mobile styles

**Pages**

- [x] Home
- [x] Downloads
- [x] News
- [x] Documentation

## Designs

**Home page:**

image

**News page:**

image

**Documentation page:**

image

**Dark mode:**

image

image

### CODE REVIEW

**Review by sorokya — CHANGES_REQUESTED** [review]
Bug with tailwind v4 and firefox sadly. See https://github.com/tailwindlabs/tailwindcss/issues/13413

image

Can we please 
- [ ] Downgrade to latest tailwind 3.x.x version

Also noticed "Recent changes" section appears differently on home page vs error page:

image

And non-doc/news 404s go to a generic error page

image

Please:
- [ ] Make all 404s use the pretty 404 page
- [ ] Format error page the same as home

**Review by sorokya — APPROVED** [review]
Amazing changes. Site looks so professional now 😎

Let's get mobile styles fixed up next

**Comment by slowSort** [comment]
Hat's off 🙌. Some sick semantic html changes

**Comment by sorokya** [comment]
> Hat's off 🙌. Some sick semantic html changes

Danny G in the house 😎

When's your PR?? 👀

**Pull request merged**
